# Generated by Django 4.2.29 on 2026-03-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientRegister_Model",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=30)),
                ("password", models.CharField(max_length=10)),
                ("phoneno", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("gender", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="detect_sybil_based_collusion_attacks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_ip", models.CharField(max_length=300)),
                ("destination_ip", models.CharField(max_length=300)),
                ("start_time", models.CharField(max_length=300)),
                ("Network_Node_Text", models.CharField(max_length=30000)),
                ("source_port", models.CharField(max_length=300)),
                ("destination_port", models.CharField(max_length=300)),
                ("flags", models.CharField(max_length=300)),
                ("site", models.CharField(max_length=300)),
                ("asn", models.CharField(max_length=300)),
                ("num_packets", models.CharField(max_length=300)),
                ("num_bytes", models.CharField(max_length=300)),
                ("Prediction", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="detection_accuracy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.CharField(max_length=300)),
                ("ratio", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="detection_ratio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.CharField(max_length=300)),
                ("ratio", models.CharField(max_length=300)),
            ],
        ),
    ]
